model:
  sdxl_model_path: "stabilityai/stable-diffusion-xl-base-1.0"
  device: "cuda"

pipeline:
  max_length: 100
  num_inference_steps: 50
  guidance_scale: 7.5

processing:
  image_size: 384  # BLIP's preferred size
  batch_size: 1